In [2]:
import scanpy as sc
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import openpyxl

In [3]:
adata = sc.read_h5ad("/Users/cyluo/Library/CloudStorage/Box-Box/MERFISH Collaboration 3/clustering3/h5ad files/gw34_scshc.h5ad")
print(adata)

AnnData object with n_obs × n_vars = 746044 × 300
    obs: 'index', 'n_counts', 'sample', 'region', 'gw', 'H1_cluster', 'H2_cluster', 'shc_result'
    obsm: 'spatial'

In [4]:
adata_obs = adata.obs
adata_obs

,index,n_counts,sample,region,gw,H1_cluster,H2_cluster,shc_result
625,2514512500007100021,33.0,UMB5900,BA17,34,0,0,0
635,2514512500007100039,43.0,UMB5900,BA17,34,0,0,0
643,2514512500007100051,19.0,UMB5900,BA17,34,0,0,0
648,2514512500007100060,17.0,UMB5900,BA17,34,0,0,0
651,2514512500007100064,21.0,UMB5900,BA17,34,0,3,1
...,...,...,...,...,...,...,...,...
1741579,2727332801334100020,93.0,UMB5900,BA17_VMSC02901,34,2,12,0
1741580,2727332801334100022,201.0,UMB5900,BA17_VMSC02901,34,0,4,1
1741582,2727332801334100030,96.0,UMB5900,BA17_VMSC02901,34,0,3,5
1741585,2727332801334100042,79.0,UMB5900,BA17_VMSC02901,34,0,0,2
1741586,2727332801334100043,147.0,UMB5900,BA17_VMSC02901,34,2,13,0

In [5]:
merged_encluster_ca_H3 = adata.obs.groupby(['region', 'H1_cluster', 'H2_cluster', 'shc_result']).size().reset_index(name='ca_count')
merged_encluster_ca_H3.to_csv("encluster_ca_H3.csv", index=False)

/var/folders/xz/tff3yvr92zz54zqk2m9jp1f00000gq/T/ipykernel_35217/3905005711.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  merged_encluster_ca_H3 = adata.obs.groupby(['region', 'H1_cluster', 'H2_cluster', 'shc_result']).size().reset_index(name='ca_count')

In [6]:
merged_encluster_H3 = adata_obs.groupby(['H1_cluster', 'H2_cluster', 'shc_result']).size().reset_index(name='H3_count')
merged_encluster_H3.to_csv("encluster_H3.csv", index=False)

In [7]:
count_ca_H3 = pd.merge(merged_encluster_ca_H3, merged_encluster_H3, on=['H1_cluster', 'H2_cluster', 'shc_result'])
count_ca_H3['percent'] = count_ca_H3['ca_count'] / count_ca_H3['H3_count']
print(count_ca_H3.head)

<bound method NDFrame.head of              region  H1_cluster  H2_cluster  shc_result  ca_count  H3_count  \
0               BA4           0           0           0      3594     63651
1               BA9           0           0           0      9800     63651
2              BA17           0           0           0     17869     63651
3    BA17_VMSC02901           0           0           0      2441     63651
4              BA22           0           0           0      7615     63651
..              ...         ...         ...         ...       ...       ...
443  BA17_VMSC02901           6          34           4       414       435
444            BA22           6          34           4         6       435
445            BA40           6          34           4         7       435
446          BA40-2           6          34           4         4       435
447           BA123           6          34           4         1       435

      percent
0    0.056464
1    0.153965
2    0.280734
3    0.038350
4    0.119637
..        ...
443  0.951724
444  0.013793
445  0.016092
446  0.009195
447  0.002299

[448 rows x 7 columns]>

In [14]:
# Check the sum of the 'percent' column for each 'H2_annotation'
percent_sum_check = count_ca_H3.groupby(['H1_cluster', 'H2_cluster', 'shc_result'])['percent'].sum().reset_index(name='percent_sum')

# Display the sums to check if any do not equal 1
print(percent_sum_check)

    H1_cluster  H2_cluster  shc_result  percent_sum
0            0           0           0          1.0
1            0           0           1          1.0
2            0           0           2          1.0
3            0           1           0          1.0
4            0           1           1          1.0
5            0           1           2          1.0
6            0           2           0          1.0
7            0           2           1          1.0
8            0           2           2          1.0
9            0           3           0          1.0
10           0           3           1          1.0
11           0           3           2          1.0
12           0           3           3          1.0
13           0           3           4          1.0
14           0           3           5          1.0
15           0           3           6          1.0
16           0           3           7          1.0
17           0           4           0          1.0
18           0           4           1          1.0
19           0           4           2          1.0
20           0           4           3          1.0
21           0           4           4          1.0
22           0           4           5          1.0
23           2          10           0          1.0
24           2          10           1          1.0
25           2          10           2          1.0
26           2          10           3          1.0
27           2          11           0          1.0
28           2          11           1          1.0
29           2          11           2          1.0
30           2          11           3          1.0
31           2          11           4          1.0
32           2          12           0          1.0
33           2          13           0          1.0
34           2          13           1          1.0
35           2          13           2          1.0
36           2          13           3          1.0
37           2          14           0          1.0
38           2          14           1          1.0
39           6          30           0          1.0
40           6          30           1          1.0
41           6          30           2          1.0
42           6          31           0          1.0
43           6          31           1          1.0
44           6          31           2          1.0
45           6          32           0          1.0
46           6          32           1          1.0
47           6          32           2          1.0
48           6          32           3          1.0
49           6          33           0          1.0
50           6          33           1          1.0
51           6          34           0          1.0
52           6          34           1          1.0
53           6          34           2          1.0
54           6          34           3          1.0
55           6          34           4          1.0

In [15]:
count_ca_H3.to_csv("H3ca_histogram.csv")