In [1]:
import scanpy as sc
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
# mers_imputed_1000.h5ad is generated by EDFig18/EDFig18A_ENVI_imputation.py
adata = sc.read_h5ad("/Users/cyluo/Library/CloudStorage/Box-Box/MERFISH Collaboration 3/clustering3/h5ad files/zenodo/mers_imputed_1000.h5ad")
print(adata)

AnnData object with n_obs × n_vars = 1020820 × 300
    obs: 'center_x', 'center_y', 'source', 'n_counts', 'sample', 'region', 'gw', 'H1_cluster', 'H2_cluster', 'H3_cluster', 'H1_annotation', 'H2_annotation'
    obsm: 'imputation', 'spatial'

In [5]:
adata_gw20 = sc.read_h5ad("/Users/cyluo/Library/CloudStorage/Box-Box/MERFISH Collaboration 3/clustering3/h5ad files/zenodo/gw20.h5ad")
print(adata_gw20)

AnnData object with n_obs × n_vars = 8044446 × 300
    obs: 'gw', 'sample', 'region', 'H1_annotation', 'H2_annotation', 'H3_annotation'
    uns: 'rank_genes_groups'
    obsm: 'spatial'

In [6]:
print(adata_gw20.obs.head())

                              gw sample region H1_annotation H2_annotation  \
2241155200012100016-FB080-F1  20  FB080     F1         EN-IT    EN-IT-L3/4
2241155200012100018-FB080-F1  20  FB080     F1         EN-IT    EN-IT-L3/4
2241155200012100021-FB080-F1  20  FB080     F1        EN-Mig      EN-IZ/L2
2241155200012100025-FB080-F1  20  FB080     F1        EN-Mig     EN-oSVZ-1
2241155200012100028-FB080-F1  20  FB080     F1         EN-IT    EN-IT-L3/4

                              H3_annotation
2241155200012100016-FB080-F1  EN-IT-L3/4-c4
2241155200012100018-FB080-F1  EN-IT-L3/4-c4
2241155200012100021-FB080-F1            NaN
2241155200012100025-FB080-F1            NaN
2241155200012100028-FB080-F1  EN-IT-L3/4-c4

In [7]:
adata_impute = adata.obsm['imputation']
adata_impute = adata_impute[list(set(adata_impute.columns) - set(adata.var.index))]
adata_impute = sc.AnnData(adata_impute)
adata_tot = sc.concat([adata, adata_impute], axis=1)
adata_tot.obs = adata.obs

In [8]:
print(adata_tot.obs.head())

                        center_x    center_y     source  n_counts sample  \
2223647900013100030  3710.701659  153.039823  FB080-O1c      16.0  FB080
2223647900013100031  3718.835391  152.200028  FB080-O1c      21.0  FB080
2223647900013100036  3696.272867  155.947341  FB080-O1c      13.0  FB080
2223647900013100039  3792.229992  154.798894  FB080-O1c      25.0  FB080
2223647900013100040  3702.410139  155.797292  FB080-O1c      15.0  FB080

                     region  gw  H1_cluster  H2_cluster  H3_cluster  \
2223647900013100030  BA17-3  20           7          38         191
2223647900013100031  BA17-3  20           2          10          52
2223647900013100036  BA17-3  20           7          38         194
2223647900013100039  BA17-3  20           1           7          39
2223647900013100040  BA17-3  20           7          38         190

                    H1_annotation H2_annotation
2223647900013100030         EN-ET    EN-ET-L6-3
2223647900013100031        EN-Mig     EN-oSVZ-1
2223647900013100036         EN-ET    EN-ET-L6-3
2223647900013100039            IN        IN-CGE
2223647900013100040         EN-ET    EN-ET-L6-3

In [58]:
adata_subset = adata_tot[adata_tot.obs['gw'] == 20].copy()
print(adata_subset.obs.head())

                        center_x    center_y     source  n_counts sample  \
2223647900013100030  3710.701659  153.039823  FB080-O1c      16.0  FB080
2223647900013100031  3718.835391  152.200028  FB080-O1c      21.0  FB080
2223647900013100036  3696.272867  155.947341  FB080-O1c      13.0  FB080
2223647900013100039  3792.229992  154.798894  FB080-O1c      25.0  FB080
2223647900013100040  3702.410139  155.797292  FB080-O1c      15.0  FB080

                     region  gw  H1_cluster  H2_cluster  H3_cluster  \
2223647900013100030  BA17-3  20           7          38         191
2223647900013100031  BA17-3  20           2          10          52
2223647900013100036  BA17-3  20           7          38         194
2223647900013100039  BA17-3  20           1           7          39
2223647900013100040  BA17-3  20           7          38         190

                    H1_annotation H2_annotation
2223647900013100030         EN-ET    EN-ET-L6-3
2223647900013100031        EN-Mig     EN-oSVZ-1
2223647900013100036         EN-ET    EN-ET-L6-3
2223647900013100039            IN        IN-CGE
2223647900013100040         EN-ET    EN-ET-L6-3

In [59]:
adata_gw20.obs['cell_id'] = adata_gw20.obs.index.str.split('-').str[0].astype(str)

In [60]:
adata_subset.obs['cell_id'] = adata_subset.obs.index.astype(str)

In [61]:
adata_subset.obs = pd.merge(
    adata_subset.obs, 
    adata_gw20.obs[['cell_id', 'H3_annotation']],  
    on='cell_id', 
    how='left'
)
print(adata_subset.obs)

            center_x      center_y     source  n_counts sample   region  gw  \
0        3710.701659    153.039823  FB080-O1c      16.0  FB080   BA17-3  20
1        3718.835391    152.200028  FB080-O1c      21.0  FB080   BA17-3  20
2        3696.272867    155.947341  FB080-O1c      13.0  FB080   BA17-3  20
3        3792.229992    154.798894  FB080-O1c      25.0  FB080   BA17-3  20
4        3702.410139    155.797292  FB080-O1c      15.0  FB080   BA17-3  20
...              ...           ...        ...       ...    ...      ...  ..
1020815  8295.833628  10863.583891   FB121-F1      37.0  FB121  GW20-3A  20
1020816  8210.255388  10863.749308   FB121-F1      49.0  FB121  GW20-3A  20
1020817  8134.934780  10865.226522   FB121-F1      68.0  FB121  GW20-3A  20
1020818  8139.416405  10865.700416   FB121-F1     114.0  FB121  GW20-3A  20
1020819  8102.591889  10864.535836   FB121-F1      36.0  FB121  GW20-3A  20

         H1_cluster  H2_cluster  H3_cluster H1_annotation H2_annotation  \
0                 7          38         191         EN-ET    EN-ET-L6-3
1                 2          10          52        EN-Mig     EN-oSVZ-1
2                 7          38         194         EN-ET    EN-ET-L6-3
3                 1           7          39            IN        IN-CGE
4                 7          38         190         EN-ET    EN-ET-L6-3
...             ...         ...         ...           ...           ...
1020815           2          10          50        EN-Mig     EN-oSVZ-1
1020816           2          13          67        EN-Mig      EN-IZ/L2
1020817           4          21         108         EN-IT    EN-IT-L3/4
1020818           2          13          68        EN-Mig      EN-IZ/L2
1020819           4          21         105         EN-IT    EN-IT-L3/4

                     cell_id  H3_annotation
0        2223647900013100030  EN-ET-L6-3-c0
1        2223647900013100031            NaN
2        2223647900013100036  EN-ET-L6-3-c0
3        2223647900013100039            NaN
4        2223647900013100040  EN-ET-L6-3-c0
...                      ...            ...
1020815  2225073501862100502            NaN
1020816  2225073501862100505            NaN
1020817  2225073501862100509  EN-IT-L3/4-c0
1020818  2225073501862100512            NaN
1020819  2225073501862100513  EN-IT-L3/4-c4

[1020820 rows x 14 columns]

In [62]:
adata_subset.obs['H3_annotation'].unique()

['EN-ET-L6-3-c0', NaN, 'EN-ET-L5/6-c3', 'EN-ET-L5/6-c4', 'EN-ET-SP-2-c0', ..., 'EN-IT-L5/6-1-c0', 'EN-IT-L5/6-1-c4', 'EN-IT-L5/6-2-c0', 'EN-IT-L3-c5', 'EN-IT-L3-c1']
Length: 38
Categories (37, object): ['EN-ET-L5/6-c0', 'EN-ET-L5/6-c1', 'EN-ET-L5/6-c2', 'EN-ET-L5/6-c3', ..., 'EN-IT-L5/6-2-c3', 'EN-IT-L6-c0', 'EN-IT-L6-c1', 'EN-IT-L6-c2']

In [63]:
clusters_of_interest1 = ["EN-IT-L3-c0", "EN-IT-L3-c3"]
clusters_of_interest2 = ["EN-IT-L3/4-c3", "EN-IT-L3/4-c0"]
clusters_of_interest3 = ["EN-ET-L5/6-c4", "EN-ET-L5/6-c3"]
clusters_of_interest4 = ['EN-ET-SP-2-c1', 'EN-ET-SP-2-c3']
adata_subset1 = adata_subset[adata_subset.obs['H3_annotation'].isin(clusters_of_interest1)]
adata_subset2 = adata_subset[adata_subset.obs['H3_annotation'].isin(clusters_of_interest2)]
adata_subset3 = adata_subset[adata_subset.obs['H3_annotation'].isin(clusters_of_interest3)]
adata_subset4 = adata_subset[adata_subset.obs['H3_annotation'].isin(clusters_of_interest4)]
print(adata_subset1.obs)

            center_x      center_y     source  n_counts sample   region  gw  \
604      3427.090166    455.893271  FB080-O1c      67.0  FB080   BA17-3  20
2054     4661.178867    328.621186  FB080-O1c      55.0  FB080   BA17-3  20
3343     3508.367679    572.701944  FB080-O1c      25.0  FB080   BA17-3  20
3895     4009.984979    644.584548  FB080-O1c     123.0  FB080   BA17-3  20
6832     4020.140090    864.354254  FB080-O1c     141.0  FB080   BA17-3  20
...              ...           ...        ...       ...    ...      ...  ..
1020562  8442.480462  10614.537059   FB121-F1     111.0  FB121  GW20-3A  20
1020588  8429.549000  10678.745183   FB121-F1     168.0  FB121  GW20-3A  20
1020665  7909.925356  10786.233840   FB121-F1     156.0  FB121  GW20-3A  20
1020708  7992.966014  10841.142037   FB121-F1     337.0  FB121  GW20-3A  20
1020764  8174.699799  10770.929992   FB121-F1      61.0  FB121  GW20-3A  20

         H1_cluster  H2_cluster  H3_cluster H1_annotation H2_annotation  \
604               4          22         111         EN-IT      EN-IT-L3
2054              4          22         112         EN-IT      EN-IT-L3
3343              4          22         110         EN-IT      EN-IT-L3
3895              4          22         110         EN-IT      EN-IT-L3
6832              4          22         112         EN-IT      EN-IT-L3
...             ...         ...         ...           ...           ...
1020562           4          22         110         EN-IT      EN-IT-L3
1020588           4          22         112         EN-IT      EN-IT-L3
1020665           4          22         110         EN-IT      EN-IT-L3
1020708           4          22         111         EN-IT      EN-IT-L3
1020764           4          22         110         EN-IT      EN-IT-L3

                     cell_id H3_annotation
604      2223647900065100246   EN-IT-L3-c3
2054     2223647900070100207   EN-IT-L3-c3
3343     2223647900118100255   EN-IT-L3-c0
3895     2223647900120100177   EN-IT-L3-c0
6832     2223647900173100164   EN-IT-L3-c3
...                      ...           ...
1020562  2225073501816100084   EN-IT-L3-c0
1020588  2225073501816100126   EN-IT-L3-c3
1020665  2225073501861100203   EN-IT-L3-c0
1020708  2225073501861100328   EN-IT-L3-c3
1020764  2225073501862100185   EN-IT-L3-c0

[16770 rows x 14 columns]

In [66]:
# Perform DE analysis
sc.tl.rank_genes_groups(adata_subset1, groupby='H3_annotation') 
sc.tl.rank_genes_groups(adata_subset2, groupby='H3_annotation') 
sc.tl.rank_genes_groups(adata_subset3, groupby='H3_annotation') 
sc.tl.rank_genes_groups(adata_subset4, groupby='H3_annotation')

WARNING: Default of the method has been changed to 't-test' from 't-test_overestim_var'

/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/scanpy/tools/_rank_genes_groups.py:582: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns[key_added] = {}
/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/anndata/_core/anndata.py:183: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

WARNING: Default of the method has been changed to 't-test' from 't-test_overestim_var'

/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/scanpy/tools/_rank_genes_groups.py:582: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns[key_added] = {}
/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/anndata/_core/anndata.py:183: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

WARNING: Default of the method has been changed to 't-test' from 't-test_overestim_var'

/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/scanpy/tools/_rank_genes_groups.py:582: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns[key_added] = {}
/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/anndata/_core/anndata.py:183: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

WARNING: Default of the method has been changed to 't-test' from 't-test_overestim_var'

/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/scanpy/tools/_rank_genes_groups.py:582: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns[key_added] = {}
/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/anndata/_core/anndata.py:183: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [67]:
result1 = adata_subset1.uns['rank_genes_groups']
result2 = adata_subset2.uns['rank_genes_groups']
result3 = adata_subset3.uns['rank_genes_groups']
result4 = adata_subset4.uns['rank_genes_groups']

de_df1 = pd.DataFrame({
    'gene': result1['names']['EN-IT-L3-c0'], 
    'log_fold_change': result1['logfoldchanges']['EN-IT-L3-c0'],
    'pvals': result1['pvals']['EN-IT-L3-c0'],
    'pvals_adj': result1['pvals_adj']['EN-IT-L3-c0']
})
de_df1['-log10_pval'] = -np.log10(de_df1['pvals_adj'])

de_df2 = pd.DataFrame({
    'gene': result2['names']['EN-IT-L3/4-c3'], 
    'log_fold_change': result2['logfoldchanges']['EN-IT-L3/4-c3'],
    'pvals': result2['pvals']['EN-IT-L3/4-c3'],
    'pvals_adj': result2['pvals_adj']['EN-IT-L3/4-c3']
})
de_df2['-log10_pval'] = -np.log10(de_df2['pvals_adj'])

de_df3 = pd.DataFrame({
    'gene': result3['names']['EN-ET-L5/6-c4'], 
    'log_fold_change': result3['logfoldchanges']['EN-ET-L5/6-c4'],
    'pvals': result3['pvals']['EN-ET-L5/6-c4'],
    'pvals_adj': result3['pvals_adj']['EN-ET-L5/6-c4']
})
de_df3['-log10_pval'] = -np.log10(de_df1['pvals_adj'])

de_df4 = pd.DataFrame({
    'gene': result4['names']['EN-ET-SP-2-c1'], 
    'log_fold_change': result4['logfoldchanges']['EN-ET-SP-2-c1'],
    'pvals': result4['pvals']['EN-ET-SP-2-c1'],
    'pvals_adj': result4['pvals_adj']['EN-ET-SP-2-c1']
})
de_df4['-log10_pval'] = -np.log10(de_df4['pvals_adj'])

/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [68]:
de_df1.to_csv('gene1000_output1.csv', index = False)
de_df2.to_csv('gene1000_output2.csv', index = False)
de_df3.to_csv('gene1000_output3.csv', index = False)
de_df4.to_csv('gene1000_output4.csv', index = False)