In [9]:
import scanpy as sc
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
adata = sc.read_h5ad("/Users/cyluo/Library/CloudStorage/Box-Box/MERFISH Collaboration 3/clustering3/h5ad files/zenodo/merscope_integrated_855.h5ad")
adata.obs

/Users/cyluo/anaconda3/envs/xuyuEnv/lib/python3.9/site-packages/anndata/_core/anndata.py:1897: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

,gw,sample,region,area,layer,H1_annotation,H2_annotation,H3_annotation,relative_height,cortical_depth
2241155200012100016,20,FB080,F1,NaN,NaN,EN-IT,EN-IT-L2/3,EN-IT-L3-V1,NaN,NaN
2241155200012100018,20,FB080,F1,NaN,NaN,EN-IT,EN-IT-L2/3,EN-IT-L3-V1,NaN,NaN
2241155200012100021,20,FB080,F1,NaN,NaN,EN-Mig,EN-L2,EN-IZ-3,NaN,NaN
2241155200012100028,20,FB080,F1,NaN,NaN,EN-IT,EN-IT-L2/3,EN-IT-L2/3-A2,NaN,NaN
2241155200012100030,20,FB080,F1,NaN,NaN,EN-IT,EN-IT-L2/3,EN-IT-L3-A,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2655870701320100026,34,UMB5900,BA40b,NaN,NaN,EN-ET,EN-ET-SP-P,EN-ET-SP-1,NaN,NaN
2655870701326100057,34,UMB5900,BA40b,NaN,NaN,EN-Mig,EN-IZ-2,EN-IZ-2,NaN,NaN
2655870701326100064,34,UMB5900,BA40b,NaN,NaN,Glia,Astro-1,Astro-1,NaN,NaN
2655870701326100070,34,UMB5900,BA40b,NaN,NaN,EC,EC,EC,NaN,NaN
2655870701326100096,34,UMB5900,BA40b,NaN,NaN,Glia,Astro-1,Astro-late3,NaN,NaN

In [4]:
filtered_adata = adata[adata.obs['H1_annotation'].isin(["EN-IT", "EN-ET", "EN-Mig"])]

In [6]:
cortical_area = pd.read_excel("cortical_area.xlsx")
print(cortical_area.head())

  sample_region cortical_area
0   UMB1117-F1a           PFC
1   UMB1117-F1b           PFC
2   UMB1117-F2a        PMC/M1
3   UMB1117-F2b        PMC/M1
4    UMB1117-P1           Par

In [ ]:
encluster_df = filtered_adata.obs
encluster_age = encluster_df.groupby('gw', observed=False).size().reset_index(name='age_count')
encluster_age.to_csv("encluster_age.csv", index=False)

In [11]:
encluster_age['gw'] = pd.Categorical(encluster_age['gw'], categories=["15", "20", "22", "34"], ordered=True)

In [12]:
labels = encluster_age['gw']
sizes = encluster_age['age_count']
colors = ["#B0F26D", "#5ebe5a", "#F066EA", "blueviolet"]

In [ ]:
plt.figure(figsize=(8, 8)) 
plt.pie(
    sizes,
    labels=labels,
    colors=colors,
    autopct='%1.1f%%', 
    startangle=0,
    wedgeprops={"edgecolor": "white"}, 
)